### ISSUE TITLE
NotImplemented Method: SourceConverter.WriteJson method called in V6.4.0

### ISSUE THREAD

**Issue by jitcompile** [jaymedavis/stripe.net#561]
The issue started appearing in v6.4.0.  Doesn't appear in v6.3.6.  Reverting my code to previous version and its working fine.

Here's a sample code to test out the issue.
`
var chargeService = new StripeChargeService("PaymentSecretKey");
var chargeOptions = new StripeChargeCreateOptions() {
                        Amount = 100,
                        Currency = "usd",
                        Description = "Charge Details", 
                        SourceTokenOrExistingSourceId = "Token",
                    };
StripeCharge stripeCharge = chargeService.Create(chargeOptions);
`

Exception:
```
System.NotImplementedException: The method or operation is not implemented.
   at Stripe.Infrastructure.SourceConverter.WriteJson(JsonWriter writer, Object value, JsonSerializer serializer)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeConvertable(JsonWriter writer, JsonConverter converter, Object value, JsonContract contract, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonConvert.SerializeObjectInternal(Object value, Type type, JsonSerializer jsonSerializer)
```

**Comment by jaymedavis** [comment]
I have a test almost identical to this. The SourceConverter should never have to write json, it should only deserialize multiple sources into a Source. How are you making your token, and what does the value of the token start with (first five chars)?

**Comment by jitcompile** [comment]
I get the token using Stripe.Js checkout. 

Configure Stripe Checkout and then open the handler.  Stripe submits token to a form and then I use your service to do a Stripe charge. The code I shared is the actual code.

The token I receive on 6.3.6 is like "tok_18gw4uBODXXXXXXXXXXXXXXX"

I don't have the tokens which failed but I believe they would be of the same format.  Please let me know if there's a debug way to share more data with you to help on this issue.

**Comment by jitcompile** [comment]
Also this is using TEST keys of Stripe and not LIVE keys. Not sure if they make any difference.

I'll try to download the source code over the weekend and will see where the method is getting called and on what condition.  Hopefully we can nail the actual place where the converter calls the writeJson method.

**Comment by jaymedavis** [comment]
Thanks - I would appreciate it, I was unable to duplicate this issue - and I haven't heard of an issue from anyone else, yet. :)

**Comment by jaymedavis** [comment]
#573 fixed this.
