### ISSUE TITLE
ConvertEpochToDateTime issue

### ISSUE THREAD

**Issue by NeoHub** [jaymedavis/stripe.net#586]
Hi,

I just updated to the last version of stripe.net (6.5.0) and I'm getting this exception when calling the ```Get``` method from ```StripeAccountService```. It seems to be related to newtonsoft.json and the ```ConvertEpochToDateTime``` implemented internally. I appreciate any help you can give me. See the error below:

```
StripeAccount providerAccount = stripeAccountService.Get(recipientId);
```

```
exceptionMessage: "Value to add was out of range. ↵Parameter name: value"
exceptionType: "System.ArgumentOutOfRangeException"
message: "An error has occurred."
stackTrace: "   at System.DateTime.Add(Double value, Int32 scale)
↵   at Stripe.Infrastructure.EpochTime.ConvertEpochToDateTime(Int64 seconds)
↵   at Stripe.Infrastructure.StripeDateTimeConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
↵   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
↵   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
↵   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
↵   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
↵   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
↵   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
↵   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
↵   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
↵   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
↵   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
↵   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
↵   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
↵   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
↵   at Stripe.StripeAccountService.Get(String accountId, StripeRequestOptions requestOptions)
↵   at TableMesa.Util.StripePayment.TransferToProvider(Int32 invoiceId, Decimal amount, Int32 providerId, String description, String providerName, String providerEmail, String token, String recipientId) in e:\projects\TableMesa\TableMesa.Util\StripePayment.cs:line 133
↵   at TableMesa.Services.TransfersController.Post(TransferDTO transfer) in e:\projects\TableMesa\TableMesa.Services\TransfersController.cs:line 37
↵   at lambda_method(Closure , Object , Object[] )
↵   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass10.<GetExecutor>b__9(Object instance, Object[] methodParameters)
↵   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.Execute(Object instance, Object[] arguments)
↵   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)
↵--- End of stack trace from previous location where exception was thrown ---
↵   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
↵   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
↵   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()
↵--- End of stack trace from previous location where exception was thrown ---
↵   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
↵   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
↵   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()
↵--- End of stack trace from previous location where exception was thrown ---
↵   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
↵   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
↵   at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__2.MoveNext()
↵--- End of stack trace from previous location where exception was thrown ---
↵   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
↵   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
↵   at System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext()
↵--- End of stack trace from previous location where exception was thrown ---
↵   at System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext()
↵--- End of stack trace from previous location where exception was thrown ---
↵   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
↵   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
↵   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__1.MoveNext()"
```

**Comment by jaymedavis** [comment]
What version are you updating from? Have you tried replacing this with a known account ID from your Stripe dashboard? Also - try wrapping the call in a try/catch(StripeException) and see if what error is coming from Stripe - that's my guess

**Comment by jaymedavis** [comment]
Share your code if you don't mind, that might help trace it down.

**Comment by NeoHub** [comment]
I'll try to catch the StripeException in a few minutes and give you a feedback. Thank you!

**Comment by NeoHub** [comment]
@jaymedavis I'm sorry for the delay, i was having too much work these days! I tried your suggestion but the expection that it raises is of ```System.ArgumentOutOfRangeException``` type. The message is this one:

```
An exception of type 'System.ArgumentOutOfRangeException' occurred in Newtonsoft.Json.dll but was not handled in user code

Additional information: Value to add was out of range.
```

And the StackTrace information is the same I placed in my first comment.

**Comment by jaymedavis** [comment]
You should get a StripeException if the call is going through. Can you paste the StripeException?

**Comment by jaymedavis** [comment]
Also please check my previous questions about what version.

**Comment by jaymedavis** [comment]
Actually, I just crawled through StripeAccount and all of it's sub entities and didn't find any DateTime's that weren't nullable already. So perhaps you have an invalid value coming back? Anyway - seeing the response in fiddler that is generating the error would help us solve this! Thanks in advance!

**Comment by NeoHub** [comment]
@jaymedavis I tried to catch the stripe exception again like this:

```
try {
   StripeAccount providerAccount = stripeAccountService.Get(recipientId);
} catch (StripeException ex) {
   var test = ex.StackTrace;
}
```

But for some reason it's not going there. I debugged the code and I'm getting just the ```System.ArgumentOutOfRangeException```. So I don't have a way to see what's happening internally :disappointed:

**Comment by jaymedavis** [comment]
Download [Fiddler](http://www.telerik.com/fiddler), start it up, run your code, and see if the web request shows up.

**Comment by jaymedavis** [comment]
If it never reached that exception, perhaps it's not firing that error on that line? Have you stepped through with the debugger?

**Comment by NeoHub** [comment]
@jaymedavis Yeah sure, I debugged it step by step, and that exact line is firing the error. I tried with Fiddler, but all I get is the same stacktrace that i copied in my first message.

It's weird because I got back to my previous stripe.net version (v2.9.0) and I'm not getting that error. I updated from that version to v6.5.0.

**Comment by jaymedavis** [comment]
Ok, if that's the case, Accounts is completely different from what it used to be due to introducing managed accounts. Be sure to read the readme on accounts again, that might help. Fiddler should have shown you a request, or not a request - it doesn't show any errors/stack trace, it just tracks web traffic.

**Comment by NeoHub** [comment]
Hey at the end we stopped using managed accounts for a while, so I didn't do anything else about it.
But i think it worth to investigate more about the issue.

**Comment by jaymedavis** [comment]
I have not heard from anyone else reporting this issue - please try fiddler and if you find something else I can work with, I can reopen.
